AWSTemplateFormatVersion: "2010-09-09"

Description: -<
    secrets-rotation-service

Transform: [
        "AWS::Serverless-2016-10-31"
]

Globals: { Function: { Runtime: "nodejs14.x", Architectures: [ "x86_64" ], MemorySize: 128, Timeout: 30, Environment: { Variables: { AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1 } } } }

Resources:
    Function:
        Type: AWS::Serverless::Function
        Properties:
            Handler: !Join [ "/", [ "src", "index.handler" ] ]
            Events: { API: {
                Type: "Api",
                Properties: {
                    Path: "/api/list-secrets",
                    Method: "GET",
                }
            } }

            Description: "..."
