AWSTemplateFormatVersion: "2010-09-09"
Transform:
    - AWS::Serverless-2016-10-31

Description: -<
    ...

Resources:
    Function:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Join [ "-", [ "Organization", "Environment", "Lambda", "Example", "Service" ] ]
            Description: "..."
            Handler: !Join [ "/", [ "src", "index.handler" ] ]
            CodeUri: "."
            MemorySize: 128
            Timeout: 30
            Runtime: "nodejs14.x"
            Environment:
                Variables:
                    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
            Events:
                API:
                    Type: HttpApi
                    Properties:
                        Path: /api/example-1
                        Method: GET
