AWSTemplateFormatVersion: "2010-09-09"

Description: -<
    secrets-rotation-service

Transform: [
        "AWS::Serverless-2016-10-31"
]

Globals: { Function: { Runtime: "nodejs14.x", Architectures: [ "x86_64" ], MemorySize: 128, Timeout: 30, Environment: { Variables: { AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1 } } } }

Resources:
    Function:
        Type: AWS::Serverless::Function
        Properties:
            Handler: !Join [ "/", [ "src", "index.handler" ] ]
            Events: { API: {
                Type: "Api",
                Properties: {
                    Path: "/api/administration",
                    Method: "GET",
                }
            } }

            Description: "..."

    API:
        Type: AWS::Serverless::HttpApi
        Properties:
            Description: "Service API Gateway"
            StageName: !Ref Stage
            AccessLogSettings:
                DestinationArn: !GetAtt Logging.Arn
                Format: >-
                    { "Request-ID": "$context.requestId", \
                    "IP": "$context.identity.sourceIp", \
                    "Caller": "$context.identity.caller", \
                    "User": "$context.identity.user", \
                    "Duration": "$context.requestTime", \
                    "HTTP-Method": "$context.httpMethod", \
                    "Endpoint": "$context.resourcePath", \
                    "Status": "$context.status", \
                    "Response-Length": "$context.responseLength" }
            # Auth: HttpApiAuth
            CorsConfiguration: True
            DisableExecuteApiEndpoint: False