version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "list-secrets-example-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-722t6cej2kdy"
s3_prefix = "list-secrets-example-2"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
