AWSTemplateFormatVersion: "2010-09-09"
Description: |
    ...
Transform: AWS::Serverless-2016-10-31

Resources:
    Logging:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Sub "${AWS::StackName}-Service-Level-Log-Group"

    Test:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./packages/example-1/template.yaml

    Administration:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./packages/administration/template.yaml

    List:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./packages/list-secrets/template.yaml

    Index:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./packages/get-secret/template.yaml