name: Deploy GH-Pages

on:
    push:
        branches: [ Development ]

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 2
                run:
                    - git checkout HEAD^
            -   name: Build
                uses: actions/setup-node@v2
                with:
                    cache: "npm"
                    node-version: "14"
                    cache-dependency-path: "**/package-lock.json"
                run: |
                    npm ci --ignore-scripts # Skip Post-Install Scripts
                    cd ./packages/ui-template
                    npm run build --production
            -   name: GitHub Pages
                if: success()
                uses: crazy-max/ghaction-github-pages@v2
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    jekyll: false
                    target_branch: Development
                    build_dir: ./packages/ui-template/build